name: Example Deploy Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate source bundle
        run: zip -r bundle.zip . -x '*.git*'
      - name: Deploy
        uses: tmshkr/blue-green-beanstalk@shared-alb
        with:
          app_name: "test-app"
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_region: ${{ vars.AWS_REGION }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          blue_env: "my-blue-env"
          green_env: "my-green-env"
          option_settings: option-settings.json
          ports: 80,443
          platform_branch_name: "Docker running on 64bit Amazon Linux 2023"
          promote: ${{ github.ref_name == 'dev' }}
          source_bundle: "bundle.zip"
          strategy: shared_alb
          version_label: ${{ github.ref_name }}-${{ github.sha }}
